# This is for LOCAL TESTING on Windows with Docker Desktop
version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
    volumes:
      - ./n8n-data:/home/node/.n8n

  nlp-service:
    build: ./nlp-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development